### PR TITLE
fix condition of financial assessment button

### PR DESCRIPTION
**Pull request by mugnivenko**
https://app.clickup.com/t/1qe4ckd

### CODE REVIEW

**Review by akeamwoodsND — CHANGES_REQUESTED** [review]
financial assessment button not showing on approved packages e.g. service-user/52c38d05-3bb0-4eee-aa40-efcfffbbd86b/packages

**Comment by mugnivenko** [comment]
we have condition like this -> isS117Client && !isS117ClientConfirmed
and for service-user/52c38d05-3bb0-4eee-aa40-efcfffbbd86b/packages
isS117Client is false

**Comment by mugnivenko** [comment]
fixed condition for link

**Review by akeamwoodsND — CHANGES_REQUESTED** [review]
service-user/b9a77788-2f8f-4a54-bcc2-e304f9e78835/packages 
doesnt have the button...

would be easier to have the logic as **something like** buttons && status !== end || status !== cancel

**Comment by mugnivenko** [comment]
condition work fine
if (!isS117Client && !isEndOrCancelled) then render
image

**Comment by akeamwoodsND** [comment]
> for those packages service-user/b9a77788-2f8f-4a54-bcc2-e304f9e78835/packages
> 
> condition work fine if (!isS117Client && !isEndOrCancelled) then render image

There is no view financial assessment button on the example i gave you?
Screenshot 2021-11-13 at 17 49 31
how is this working fine?

**Comment by mugnivenko** [comment]
> > for those packages service-user/b9a77788-2f8f-4a54-bcc2-e304f9e78835/packages
> > condition work fine if (!isS117Client && !isEndOrCancelled) then render image
> 
> There is no view financial assessment button on the example i gave you? Screenshot 2021-11-13 at 17 49 31 how is this working fine?

I asked Burak about this condition. And he sad that it is right condition (not isS117Client and not end or canceled)

**Pull request merged**
