### PR TITLE
Feature/review package details

### PR DESCRIPTION
**Pull request by mugnivenko**

### CODE REVIEW

**Comment by mugnivenko** [comment]
has changes from CorePackageDetails

**Review by akeamwoodsND — CHANGES_REQUESTED** [review]
Text area with counter missing counter (look at storybook):

Screenshot 2021-09-30 at 14 40 55

**Review by akeamwoodsND — CHANGES_REQUESTED** [review]
Select component has two chevron icons:

Screenshot 2021-09-30 at 14 44 23

**Review by akeamwoodsND — CHANGES_REQUESTED** [review]
clicking the chevron in the select box prevents opening options. set `pointer-events: none;` in the css
Screenshot 2021-09-30 at 15 10 53

**Pull request merged**
