### PR TITLE
fix supplier search box

### PR DESCRIPTION
**Pull request by mugnivenko**
https://app.clickup.com/t/1k1a70n

### CODE REVIEW

**Review by akeamwoodsND — CHANGES_REQUESTED** [review]
bug, steps to reproduce:

1. go to supplier lookup e.g. **care-package/30135656-a6fb-4eec-b439-3fdb00824b1d/broker-package**
2. type in the search box
3. press the search button
4. press the clear button
5. type in the search box

Notice how it has gone back to auto search.

**Comment by mugnivenko** [comment]
> bug, steps to reproduce:
> 
> 1. go to supplier lookup e.g. **care-package/30135656-a6fb-4eec-b439-3fdb00824b1d/broker-package**
> 2. type in the search box
> 3. press the search button
> 4. press the clear button
> 5. type in the search box
> 
> Notice how it has gone back to auto search.

fixed

**Review by akeamwoodsND — CHANGES_REQUESTED** [review]
similar bug to before:
1. go to supplier look up
2. **select** a supplier
3. remove suppliuer
4. type in search box
5. notice how it has gone to auto search

**Comment by mugnivenko** [comment]
> similar bug to before:
> 
> 1. go to supplier look up
> 2. **select** a supplier
> 3. remove suppliuer
> 4. type in search box
> 5. notice how it has gone to auto search

fixed

**Review by akeamwoodsND — CHANGES_REQUESTED** [review]
Screenshot 2021-11-10 at 13 06 26
type in a random string which is **not** a supplier. notice how it does not show the search page? it should show '0 results found'

**Comment by mugnivenko** [comment]
i added InsetText component for that case
image

**Pull request merged**
