### PR TITLE
[NORMAL] fix cancel button style

### PR DESCRIPTION
**Pull request by mugnivenko**
https://app.clickup.com/t/1wtwaar

image
image

### CODE REVIEW

**Review by akeamwoodsND — CHANGES_REQUESTED** [review]
it is good UX to have the main button on the right. Put submit button on right please

**Comment by mugnivenko** [comment]
image

**Review by akeamwoodsND — CHANGES_REQUESTED** [review]
stretch buttons here to take up al width/make same size (use flex or something not hardcoded widths)
Screenshot 2021-12-08 at 09 09 15

**Comment by mugnivenko** [comment]
image

**Pull request merged**
